sudo: false
dist: trusty
language: php
cache:
  apt: true
env:
  global:
  - EE_VERSION=master
  - WP_VERSION=latest WP_MULTISITE=0
matrix:
  include:
  - php: 5.3
    dist: precise
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 5.6
    env: WP_MULTISITE=1
  - php: 5.6
    env: WP_VERSION=4.1
  - php: 5.6
    env: WP_VERSION=4.1 WP_MULTISITE=1
  - php: 7.0
    env: WP_MULTISITE=1
  - php: 7.0
  - php: 7.1
    env: WP_MULTISITE=1
  fast_finish: true
before_install:
- |
  if [[ "$SKIP_XDEBUG_REMOVE" != "true" ]]; then
    phpenv config-rm xdebug.ini
    echo "xdebug removed";
  fi
before_script:
- bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- . tests/bin/setup-addon-tests.sh
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- |
    # Install the specified version of PHPUnit depending on the PHP version:
    if [[ -n "$TRAVIS_PHP_VERSION" ]]; then
      case "$TRAVIS_PHP_VERSION" in
        7.1|7.0|nightly)
          echo "Using PHPUnit 6.1"
          composer global require "phpunit/phpunit=6.1.*"
          ;;
        5.6|5.5|5.4|5.3)
          echo "Using PHPUnit 4.8"
          composer global require "phpunit/phpunit=4.8.*"
          ;;
        5.2)
          # Do nothing, use default PHPUnit 3.6.x
          echo "Using default PHPUnit, hopefully 3.6"
          ;;
        *)
          echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
          exit 1
          ;;
      esac
    fi
- mysql --version
- phpunit --version
- phpenv versions
script: cd tests; phpunit;
notifications:
  slack:
    rooms:
      secure: "EZUSCx79ula3gdwVRivszWkze5Ux/iGWvpvRLtpgCtpdNPNnA5ECEuVDEJy7P2THfEPmGOB0sO9B8hntUsU2iY6GK3j5PKCWrWx6g9DX40sFe0GhzxGWXebJg9SSsFJy2BIXQrufLEQgkfKa9wxswl892qyslE+3kl8sipPBAxdAMmm9iSizq3goF6Mpbi54vyCA9rRHRc+XnlokeDvKpdSOgSKEBC6MHOFFsfnLa48QHqyqUgUBEqMHA6+h4NfVcnOdsp6qUd7v3eNUrF/HEivCUpGnjAT4qnaxARcqLKezG4MJRxxd2DFVdU061rSc/Xd+Z9gOIHCt3G35hzzx1XBODycg8gAgTMPA3XNCBgCKxB6pIDtOy7yw7VWAKkfLhQbWQQsn2sMdXZjyxCXoYnTNdcCdpXHTCNOYkQ12udk/bXUf7p/M16BphO9z4VofP7r/Tg8UEV5F6JFnjJCFCDKENn0/Ivp27XCbCVl9iaUnIVC2AYRtCe5mFcKVmnav1PXWcPA5dB6I4/dbBASAMJO7ZM5RiZ7Qf+LJLAVU4NE46zwQxjZ76XNwdmGaEKhhlJfz5zFqnu+Qr7QtQ7vLPqRB8L206OQ7YZGzBXMkaskTQ1fcKVWYOyArYulMAHozxcvOT340baJG3EsRyQFem/tX+qQE5ETgB9aai55KpaA="
    on_success: always
    on_failure: always
    on_start: always
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
      - "%{commit_message}"

